/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type NoName3 = string;
export type NoName4 = string[];
export type NoName5 = string[];
export type NoName7 = string[];
export type NoName8 = string[];
export type NoName10 = string;
export type NoName12 = string[];
export type NoName13 = string;
export type NoName11 = {
  paths: NoName12;
  value: NoName13;
}[];
export type NoName15 = string[];
export type NoName16 = string;
export type NoName14 = {
  extensions: NoName15;
  value: NoName16;
}[];
export type NoName17 = string[];
export type NoName18 = string;
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type NoName20 = string;

export interface ReportW0SJp {
  port: HTTP;
  response: NoName;
  static: NoName2;
  cors: CORS;
  views: NoName18;
  errorpage: NoName19;
  logger: Logger;
  mail: EMail;
}
export interface NoName {
  header: NoName1;
}
export interface NoName1 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
}
export interface NoName2 {
  root: NoName3;
  extensions?: NoName4;
  indexes?: NoName5;
  headers: NoName6;
}
export interface NoName6 {
  mime: MIME;
  cache_control?: NoName9;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: NoName7;
}
export interface MIME2 {
  [k: string]: NoName8;
}
export interface NoName9 {
  default: NoName10;
  path: NoName11;
  extension: NoName14;
}
export interface CORS {
  allow_origins: NoName17;
}
export interface NoName19 {
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
}
export interface Logger {
  path: NoName20;
}
export interface EMail {
  smtp: string;
  user: string;
  password: string;
  port: number;
  from: string;
  to: string;
}
