/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName = string[];
export type NoName2 = string;
export type View = string;

export interface JavaScript {
  allow_origins: NoName;
  mail: NoName1;
}
export interface NoName1 {
  title: NoName2;
  view: View;
}
