/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string[];
export type NoName3 = string;
export type View = string;

export interface NoName {
  allow_origins: NoName1;
  mail: NoName2;
}
export interface NoName2 {
  title: NoName3;
  view: View;
}
