/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type NoName3 = string;
export type NoName4 = string[];
export type NoName5 = string[];
export type NoName8 = string;
export type NoName10 = string[];
export type NoName11 = string;
export type NoName9 = {
  paths: NoName10;
  value: NoName11;
}[];
export type NoName13 = string[];
export type NoName14 = string;
export type NoName12 = {
  extensions: NoName13;
  value: NoName14;
}[];
export type NoName15 = string;
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type NoName17 = string;
export type NoName18 = string[];
export type NoName20 = string;
export type View = string;
export type NoName22 = string[];
export type NoName24 = string;
export type View1 = string;

export interface ReportW0SJp {
  port: HTTP;
  response: NoName;
  static: NoName2;
  views: NoName15;
  errorpage: NoName16;
  logger: Logger;
  mail: EMail;
  js: JavaScript;
  referrer: NoName21;
}
export interface NoName {
  header: NoName1;
}
export interface NoName1 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
}
export interface NoName2 {
  root: NoName3;
  extensions?: NoName4;
  indexes?: NoName5;
  headers: NoName6;
}
export interface NoName6 {
  mime: MIME;
  cache_control?: NoName7;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: unknown;
}
export interface MIME2 {
  [k: string]: unknown;
}
export interface NoName7 {
  default: NoName8;
  path: NoName9;
  extension: NoName12;
}
export interface NoName16 {
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
}
export interface Logger {
  path: NoName17;
}
export interface EMail {
  smtp: string;
  user: string;
  password: string;
  port: number;
  from: string;
  to: string;
}
export interface JavaScript {
  allow_origins: NoName18;
  mail: NoName19;
}
export interface NoName19 {
  title: NoName20;
  view: View;
}
export interface NoName21 {
  allow_origins: NoName22;
  mail: NoName23;
}
export interface NoName23 {
  title: NoName24;
  view: View1;
}
